server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: empleado-service
          uri: lb://empleado-service
          predicates:
           - Path=/api/empleados/**
        - id: categoria-service
          uri: lb://categoria-service
          predicates:
            - Path=/api/categorias/**
        - id: marcaAsistencia-service
          uri: lb://marcaAsistencia-service
          predicates:
            - Path=/api/asistencias/**
        - id: horasExtras-service
          uri: lb://horasExtras-service
          predicates:
            - Path=/api/horas-extras/**