server:
  port: 8080

eureka:
  instance:
    hostname: gateway-service
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            allowCredentials: false
      routes:
        - id: empleado-service
          uri: lb://empleado-service
          predicates:
            - Path=/api/empleados/**
        - id: categoria-service
          uri: lb://categoria-service
          predicates:
            - Path=/api/categorias/**
        - id: asistencia-service
          uri: lb://asistencia-service
          predicates:
            - Path=/api/asistencias/**
        - id: extras-service
          uri: lb://extras-service
          predicates:
            - Path=/api/horas-extras/**
        - id: justificativo-service
          uri: lb://justificativo-service
          predicates:
            - Path=/api/justificativos/**
        - id: planilla-service
          uri: lb://planilla-service
          predicates:
            - Path=/api/planillas-sueldos/**

