server:
  port: 8080  
eureka:
  client:
    fetch-registry: true # Habilita la obtención del registro de servicios desde Eureka
    register-with-eureka: true # Registra este servicio en Eureka
    service-url:
      default-zone: http://eureka-service:8761/eureka/ # URL del servidor Eureka en el clúster de Kubernetes
 instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  profiles:
    active: dev